### ISSUE TITLE
Request: Feature Gate Metadata

### ISSUE THREAD

**Issue by leo-vetster** [statsig-io/php-sdk#11]
Hi team, 

I wonder if php-sdk could support Feature Gate Metadata e.g. `getReason` & `ruleID` like the one in [java sdk](https://docs.statsig.com/server/javaSdk#retrieving-feature-gate-metadata)

Thank you

**Comment by weihao-statsig** [comment]
Yes, we support, check here: https://github.com/statsig-io/php-sdk/blob/main/src/StatsigServer.php#L58

**Comment by tore-statsig** [comment]
Use `getFeatureGate`

https://github.com/statsig-io/php-sdk/blob/main/src/FeatureGate.php
