### ISSUE TITLE
Request: Vendor binaries for sync and send

### ISSUE THREAD

**Issue by ziming** [statsig-io/php-sdk#6]
Hi, Totally new to statsig & product analytics stuffs here, but wanted to give Statsig a try to learn more about this area

As I work with the PHP Laravel framework, I decided to write a simple laravel package wrapper for Statsig for easier development. but faced some issues because send.php and sync.php are not vendor binaries (hence hidden deep within layers of vendor directories. Which kind of make it troublesome for me to reference them in the following 2 commands of my package

https://github.com/ziming/laravel-statsig/blob/main/src/Commands/StatsigSyncCommand.php
https://github.com/ziming/laravel-statsig/blob/main/src/Commands/StatsigSendCommand.php

Hence I like to suggest the following:

- create statsig-sync & statsig-send binaries (removing the .php extension from the filename)
- Make those 2 files executable and add #!/usr/bin/env php to the top of those 2 files
- declare them in your composer.json "bin" key (See the references links below)

Some references that you might find useful:

https://getcomposer.org/doc/articles/vendor-binaries.md

An example from PHPStan

https://github.com/phpstan/phpstan/blob/1.11.x/composer.json
https://github.com/phpstan/phpstan/blob/1.11.x/phpstan

What all this does is that when others composer require your package, statsig-sync and statsig-send command will be installed in their project vendor/bin folder, making it much easier for your users to call the send and sync command as they can now just do ./vendor/bin/statsig-sync or ./vendor/bin/statsig-send instead of php ./vendor/statsig/statsigsdk/src/sync.php (which is also more prone to things breaking if you change your folder names)

Thank you

**Comment by dan-loomb** [comment]
I have added this to the backlog

**Comment by tore-statsig** [comment]
Thanks for the detailed feedback - this is a great idea!
